/**
 * Single source of truth for every user-facing Turkish string.
 *
 * Code identifiers, enum keys (in constants.ts), DB column names and console
 * logs stay in English — only what the USER sees lives here. Components must
 * reference `S` and the *_LABELS maps below instead of hardcoding Turkish text.
 *
 * Trading jargon (Order Block, FVG, Killzone, premium/discount, CHoCH/BOS) is
 * deliberately kept in its industry-standard English form — Turkish ICT traders
 * use these terms in English.
 */
import type {
  ExpenseCategory,
  HtfBias,
  Session,
  SetupType,
  TradeResult,
  Zone,
} from "./constants";

/** Setup type display labels (enum keys stay English in constants.ts). */
export const SETUP_LABELS: Record<SetupType, string> = {
  "Range Play (Premium/Discount reaction)": "Range Oyunu (Premium/Discount tepkisi)",
  "OTE (Optimal Trade Entry)": "OTE (Optimal Giriş)",
  "Order Block (OB)": "Order Block (OB)",
  "Fair Value Gap (FVG)": "Fair Value Gap (FVG)",
  "Breaker Block": "Breaker Block",
  "Mitigation Block": "Mitigation Block",
  "Liquidity Sweep / Grab": "Likidite Süpürmesi",
  "Turtle Soup": "Turtle Soup",
  "HTF FVG Continuation": "HTF FVG Devamı",
  Other: "Diğer",
};

export const SESSION_LABELS: Record<Session, string> = {
  asia: "Asya",
  london: "Londra",
  ny_am: "NY Sabah",
  ny_pm: "NY Öğleden Sonra",
  other: "Diğer",
};

export const ZONE_LABELS: Record<Zone, string> = {
  premium: "Premium",
  discount: "İndirim (Discount)",
  equilibrium: "Denge (EQ)",
};

export const HTF_BIAS_LABELS: Record<HtfBias, string> = {
  bullish: "Yükseliş",
  bearish: "Düşüş",
  neutral: "Nötr",
};

export const RESULT_LABELS: Record<TradeResult, string> = {
  win: "Kazanç",
  loss: "Zarar",
  breakeven: "Başabaş",
};

export const STATUS_LABELS = {
  planned: "Planlandı",
  open: "Açık",
  closed: "Kapalı",
} as const;

export const MISTAKE_LABELS: Record<string, string> = {
  "FOMO entry (no setup)": "FOMO girişi (setup yok)",
  "Moved stop loss": "Stop'u kaydırdım",
  "No confirmation": "Onay yoktu",
  "Over-risked (above plan)": "Plandan fazla risk",
  "Revenge trade": "İntikam işlemi",
  "Entered against HTF bias": "HTF trende karşı girdim",
  "Closed early / cut winner": "Karı erken kapattım",
  "Held loser past stop": "Zararı stop'tan sonra tuttum",
  "Traded outside killzone": "Killzone dışında işlem",
};

export const EXPENSE_CATEGORY_LABELS: Record<ExpenseCategory, string> = {
  streaming: "Yayın (Netflix/YouTube vb.)",
  music: "Müzik",
  software: "Yazılım / Araçlar",
  housing: "Konut (Kira/Aidat)",
  utilities: "Faturalar (elektrik/su/internet)",
  phone: "Telefon / Hat",
  fitness: "Spor / Sağlık",
  transport: "Ulaşım",
  other: "Diğer",
};

/** Look up a display label, falling back to the raw value (custom entries). */
export const label = (map: Record<string, string>, key: string) => map[key] ?? key;

export const S = {
  tabs: {
    dashboard: "Özet",
    trades: "İşlemler",
    calendar: "Takvim",
    stats: "İstatistik",
    settings: "Ayarlar",
  },
  common: {
    save: "Kaydet",
    cancel: "İptal",
    confirm: "Onayla",
    delete: "Sil",
    edit: "Düzenle",
    back: "Geri",
    loading: "Yükleniyor...",
    search: "Ara",
    filter: "Filtrele",
    all: "Tümü",
    none: "—",
    signOut: "Çıkış Yap",
    export: "Dışa Aktar",
    theme: "Tema",
    dark: "Koyu",
    light: "Açık",
  },
  auth: {
    tagline: "Her işlemi kaydet. Para kazandıranı bul. Kaybettireni ele.",
    email: "E-posta",
    password: "Şifre",
    passwordHint: "En az 6 karakter (bu cihazda lokal saklanır)",
    signIn: "Giriş yap",
    signUp: "Hesap oluştur",
    toSignUp: "Hesabın yok mu? Oluştur",
    toSignIn: "Zaten hesabın var mı? Giriş yap",
    or: "veya",
    guest: "Misafir olarak devam et",
    guestSession: "Lokal misafir oturumu",
    localAccount: "Lokal hesap",
    badEmail: "Geçerli bir e-posta gir",
    shortPassword: "Şifre en az 6 karakter olmalı",
    exists: "Bu e-posta ile zaten bir hesap var",
    wrong: "E-posta veya şifre hatalı",
  },
  trade: {
    new: "Yeni İşlem",
    detail: "İşlem Detayı",
    editTitle: "İşlemi Düzenle",
    quickLog: "Hızlı Kayıt (AI)",
    symbol: "Parite",
    direction: "Yön",
    long: "Alış (Long)",
    short: "Satış (Short)",
    setupType: "Setup Tipi",
    confluences: "Konfluanslar",
    zone: "Bölge",
    session: "Seans",
    htfBias: "HTF Yönü",
    biasTf: "Yön Zaman Dilimi",
    entryTf: "Giriş Zaman Dilimi",
    rangeHigh: "Range Tepe (ops.)",
    rangeLow: "Range Dip (ops.)",
    entry: "Giriş",
    stop: "Stop",
    takeProfit: "Hedef",
    exit: "Çıkış",
    risk: "Risk %",
    plannedRR: "Planlanan R:R",
    realizedR: "Gerçekleşen R",
    pnl: "K/Z",
    entryReason: "Giriş Nedeni",
    notes: "Notlar",
    addDetail: "Detay ekle (opsiyonel)",
    hideDetail: "Detayı gizle",
    save: "Kaydet",
    savePlanned: "Planlı olarak kaydet",
    closeTrade: "İşlemi Kapat",
    editNotes: "Notları Düzenle",
    saveNotes: "Notları Kaydet",
    notFound: "İşlem bulunamadı",
    autoSession: "Seans giriş saatinden otomatik belirlendi",
    beforeShot: "Öncesi ekran görüntüsü",
    afterShot: "Sonrası ekran görüntüsü",
    mistakesHonest: "Yapılan hatalar (dürüst ol!)",
    result: "Sonuç",
    realizedResult: "Gerçekleşen sonuç",
    cleanExec: "✓ Temiz uygulama — hata etiketlenmemiş",
    riskOver: (max: number) => `Maks %${max} üstünde!`,
    riskHint: (def: number, max: number) => `Varsayılan %${def} · maks %${max}`,
    reasonMin: "En az 10 karakter",
    overMaxRiskNotice: "Riskin maks limitinin üstünde — yine de kaydedebilirsin.",
  },
  swipe: {
    label: "Kuralıma uygun — işlemi kaydet",
    done: "Kaydediliyor...",
    rulesTitle: "Hatırlatma (zorunlu değil)",
    rules: [
      "HTF yönü net ve onunla aynı yöndeyim",
      "Hedeflenecek likidite var",
      "Girişim geçerli bir setup'ta (fiyatı kovalamıyorum)",
      "Riskim maks riskimin altında",
      "Stop ve hedefimi biliyorum",
    ],
  },
  result: {
    win: "Kazanç",
    loss: "Zarar",
    breakeven: "Başabaş",
    planned: "Planlandı",
    open: "Açık",
    closed: "Kapalı",
    mistakes: "Hatalar",
  },
  list: {
    searchPlaceholder: "Parite, setup, not ara",
    clearFilters: "Tüm filtreleri temizle",
    onlyMistakes: "Sadece hatalı işlemler",
    count: (n: number) => `${n} işlem`,
    result: "Sonuç",
    period: "Dönem",
    allTime: "Tüm zamanlar",
    setupAll: "Tüm setuplar",
    wins: "Kazançlar",
    losses: "Zararlar",
  },
  dash: {
    netR: "Net R",
    winRate: "Kazanma Oranı",
    expectancy: "Beklenti",
    expectancySub: "R / işlem",
    netPnl: "Net K/Z",
    accountCcy: "hesap birimi",
    streak: "Seri",
    current: "mevcut",
    openPlanned: "Açık / Planlı",
    totalSuffix: (n: number) => `${n} toplam`,
    closedSuffix: (n: number) => `${n} kapalı`,
    bestWorst: (best: string, worst: string) =>
      `En iyi ${best} · En kötü ${worst} (bu dönem)`,
    equity: "Sermaye Eğrisi · kümülatif R",
    equityEmpty: "Eğrini büyütmek için birkaç işlem kapat",
  },
  stats: {
    winRate: "Kazanma Oranı",
    totalR: "Toplam R",
    expectancy: "Beklenti (R/işlem)",
    streak: "Seri",
    equityCurve: "Sermaye Eğrisi",
    bestSetup: "En İyi Setup",
    worstSetup: "En Kötü Setup",
    bySetup: "Setup'a Göre Kazanma Oranı",
    bySession: "Seansa Göre",
    byConfluence: "Konfluansa Göre",
    mistakesRanked: "En Sık Hatalar",
    cleanVsMistake: "Temiz İşlemler vs Hatalı İşlemler",
    cleanCol: "Temiz İşlemler",
    mistakeCol: "Hatalı İşlemler",
    edge: "işlem başına ort. R",
    notEnough: "Henüz yeterli veri yok",
    emptyTitle: "Henüz kapalı işlem yok",
    emptySub:
      "Birkaç işlem kapat; setup, seans ve konfluans bazında avantajın burada görünür.",
    noMistakes: "🎯 Hiç hata etiketlenmemiş. Böyle devam.",
  },
  calendar: {
    weekdays: ["Pz", "Pt", "Sa", "Ça", "Pe", "Cu", "Ct"],
    monthSuffix: "bu ay",
    noTradesDay: "Bu gün işlem yok.",
    hint: "Bir güne dokunup o günün işlemlerini gör. Daha yeşil = daha çok R kazanç, daha kırmızı = daha çok R kayıp.",
  },
  settings: {
    account: "Hesap",
    guest: "Misafir",
    riskDefaults: "Risk Varsayılanları",
    defaultRisk: "Varsayılan risk %",
    maxRisk: "Maks risk %",
    startingBalance: "Başlangıç bakiyesi (hesap birimi)",
    appearance: "Görünüm",
    customSetups: "Özel Setuplar",
    customConfluences: "Özel Konfluanslar",
    setupPlaceholder: "örn. SMT Divergence",
    confluencePlaceholder: "örn. DXY korelasyonu",
    noneAdded: "Henüz eklenmedi.",
    export: "Dışa Aktar",
    data: "Veri",
    reseed: "Sıfırla & örnek veriyi yükle",
    reseedTitle: "Sıfırla & yeniden yükle?",
    reseedBody: "Bu işlem tüm kayıtları siler ve 10 örnek işlemi geri yükler.",
    footer: "SMC Journal · tüm veriler bu cihazda lokal saklanır",
    nothingExport: "Aktarılacak bir şey yok",
    nothingExportBody: "Önce bir işlem kaydet.",
    exportFail: "Dışa aktarma başarısız",
    exportFailBody: "Dışa aktarma dosyası oluşturulamadı.",
  },
  empty: {
    trades: "Henüz işlem yok. İlk işlemini kaydet.",
    logFirst: "İlk işlemi kaydet",
    noMatch: "Sonuç yok",
    noMatchSub: "Filtreleri veya aramanı temizlemeyi dene.",
  },
  del: {
    title: "İşlem silinsin mi?",
    today: "Bu, bugünün işlemlerinden biri. Silme işlemi kalıcıdır.",
    body: "Bu işlem kalıcı olarak silinecek.",
    cantClose: "Kapatılamıyor",
    alreadyClosed: "Bu işlem zaten kapalı.",
  },
  expense: {
    tab: "Giderler",
    add: "Gider Ekle",
    editTitle: "Gideri Düzenle",
    detail: "Gider Detayı",
    name: "İsim",
    amount: "Tutar",
    currency: "Para Birimi",
    category: "Kategori",
    cycle: "Döngü",
    monthly: "Aylık",
    yearly: "Yıllık",
    billingDay: "Ödeme Günü",
    billingDayOf: (n: number) => `her ayın ${n}'i`,
    paymentMethod: "Ödeme Yöntemi",
    paymentPlaceholder: "örn. Kredi kartı, Otomatik ödeme",
    active: "Aktif",
    pause: "Durdur",
    resume: "Devam ettir",
    paused: "Durduruldu",
    addDetail: "Detay ekle (opsiyonel)",
    hideDetail: "Detayı gizle",
    notes: "Notlar",
    save: "Kaydet",
    delete: "Tamamen sil",
    deleteTitle: "Gider silinsin mi?",
    deleteBody: "Bu gider kalıcı olarak silinecek. (Sadece durdurmak için 'Durdur' kullan.)",
    monthlyTotal: "Aylık Toplam",
    yearlyTotal: "Yıllık Toplam",
    activeSubs: "Aktif Abonelik",
    upcoming: "Yaklaşan Ödemeler",
    byCategory: "Kategoriye Göre",
    inDays: (n: number) => `${n} gün sonra`,
    today: "Bugün",
    tomorrow: "Yarın",
    approx: "≈",
    empty: "Henüz gider eklenmedi. İlk sabit giderini ekle.",
    emptyAdd: "İlk gideri ekle",
    notFound: "Gider bulunamadı",
    fxTitle: "Para Birimi & Kur",
    fxBase: "Ana Para Birimi",
    fxUsd: "USD → TRY",
    fxEur: "EUR → TRY",
    fxHint: "Manuel kur (otomatik çekme yok, offline kalır).",
    dashLine: (amount: string) => `Bu ayki sabit giderin: ${amount}.`,
    dashRNeed: (r: string) => `Karşılamak için ≈ ${r} gerekiyor.`,
    import: "İçe Aktar (JSON)",
    importHint: "Başka cihazdan dışa aktardığın gider JSON'unu yükle.",
  },
  data: {
    importDone: "İçe aktarıldı",
    importDoneCount: (n: number) => `${n} gider eklendi/güncellendi.`,
    importNone: "Dosyada geçerli gider bulunamadı.",
    importFail: "İçe aktarma başarısız",
    importFailBody:
      "Geçerli bir JSON dosyası seç (uygulamadan dışa aktardığın gider dosyası).",
  },
} as const;
