/**
 * Single source of truth for every user-facing Turkish string.
 *
 * Code identifiers, enum keys (in constants.ts), DB column names and console
 * logs stay in English — only what the USER sees lives here. Components must
 * reference `S` and the *_LABELS maps below instead of hardcoding Turkish text.
 */
import type { ExpenseCategory } from "./constants";

export const EXPENSE_CATEGORY_LABELS: Record<ExpenseCategory, string> = {
  streaming: "Yayın (Netflix/YouTube vb.)",
  music: "Müzik",
  software: "Yazılım / Araçlar",
  housing: "Konut (Kira/Aidat)",
  utilities: "Faturalar (elektrik/su/internet)",
  phone: "Telefon / Hat",
  fitness: "Spor / Sağlık",
  transport: "Ulaşım",
  other: "Diğer",
};

/** Look up a display label, falling back to the raw value (custom entries). */
export const label = (map: Record<string, string>, key: string) => map[key] ?? key;

export const S = {
  tabs: {
    settings: "Ayarlar",
  },
  common: {
    save: "Kaydet",
    cancel: "İptal",
    confirm: "Onayla",
    delete: "Sil",
    edit: "Düzenle",
    back: "Geri",
    loading: "Yükleniyor...",
    search: "Ara",
    filter: "Filtrele",
    all: "Tümü",
    none: "—",
    signOut: "Çıkış Yap",
    export: "Dışa Aktar",
    theme: "Tema",
    dark: "Koyu",
    light: "Açık",
  },
  auth: {
    tagline: "Sabit giderlerini kaydet. Nereye gittiğini her zaman bil.",
    email: "E-posta",
    password: "Şifre",
    passwordHint: "En az 6 karakter (bu cihazda lokal saklanır)",
    signIn: "Giriş yap",
    signUp: "Hesap oluştur",
    toSignUp: "Hesabın yok mu? Oluştur",
    toSignIn: "Zaten hesabın var mı? Giriş yap",
    or: "veya",
    guest: "Misafir olarak devam et",
    guestSession: "Lokal misafir oturumu",
    localAccount: "Lokal hesap",
    badEmail: "Geçerli bir e-posta gir",
    shortPassword: "Şifre en az 6 karakter olmalı",
    exists: "Bu e-posta ile zaten bir hesap var",
    wrong: "E-posta veya şifre hatalı",
  },
  settings: {
    account: "Hesap",
    guest: "Misafir",
    appearance: "Görünüm",
    export: "Dışa Aktar",
    data: "Veri",
    footer: "Giderler · tüm veriler bu cihazda lokal saklanır",
    nothingExport: "Aktarılacak bir şey yok",
    nothingExportBody: "Önce bir gider kaydet.",
    exportFail: "Dışa aktarma başarısız",
    exportFailBody: "Dışa aktarma dosyası oluşturulamadı.",
  },
  expense: {
    tab: "Giderler",
    add: "Gider Ekle",
    editTitle: "Gideri Düzenle",
    detail: "Gider Detayı",
    name: "İsim",
    amount: "Tutar",
    currency: "Para Birimi",
    category: "Kategori",
    cycle: "Döngü",
    monthly: "Aylık",
    yearly: "Yıllık",
    billingDay: "Ödeme Günü",
    billingDayOf: (n: number) => `her ayın ${n}'i`,
    paymentMethod: "Ödeme Yöntemi",
    paymentPlaceholder: "örn. Kredi kartı, Otomatik ödeme",
    active: "Aktif",
    pause: "Durdur",
    resume: "Devam ettir",
    paused: "Durduruldu",
    addDetail: "Detay ekle (opsiyonel)",
    hideDetail: "Detayı gizle",
    notes: "Notlar",
    save: "Kaydet",
    delete: "Tamamen sil",
    deleteTitle: "Gider silinsin mi?",
    deleteBody: "Bu gider kalıcı olarak silinecek. (Sadece durdurmak için 'Durdur' kullan.)",
    monthlyTotal: "Aylık Toplam",
    yearlyTotal: "Yıllık Toplam",
    activeSubs: "Aktif Abonelik",
    upcoming: "Yaklaşan Ödemeler",
    byCategory: "Kategoriye Göre",
    inDays: (n: number) => `${n} gün sonra`,
    today: "Bugün",
    tomorrow: "Yarın",
    approx: "≈",
    empty: "Henüz gider eklenmedi. İlk sabit giderini ekle.",
    emptyAdd: "İlk gideri ekle",
    notFound: "Gider bulunamadı",
    fxTitle: "Para Birimi & Kur",
    fxBase: "Ana Para Birimi",
    fxUsd: "USD → TRY",
    fxHint: "Manuel kur (otomatik çekme yok, offline kalır).",
    dashLine: (amount: string) => `Bu ayki sabit giderin: ${amount}.`,
    dashRNeed: (r: string) => `Karşılamak için ≈ ${r} gerekiyor.`,
    import: "İçe Aktar (JSON)",
    importHint: "Başka cihazdan dışa aktardığın gider JSON'unu yükle.",
    reviewSection: "Gözden Geçir",
    stillUsing: "Hâlâ kullanıyor musun?",
    confirmContinue: "Devam Ediyorum",
    savingsIfCancelled: (amount: string) => `Durdurursan yılda ${amount} biriktirirsin.`,
    priceHistory: "Fiyat Geçmişi",
    priceIncreaseSummary: (pct: string, date: string) =>
      `${date}'ten beri %${pct} değişti.`,
    noChange: "Fiyat hiç değişmedi.",
    digestTitle: "Bu Ay Ne Değişti",
    digestNewLine: (n: number) => `${n} yeni gider eklendi.`,
    digestPriceLine: (name: string, pct: string) => `${name}: %${pct} değişti.`,
    digestPausedLine: (n: number) => `${n} gider şu an durdurulmuş durumda.`,
    digestDismiss: "Anladım",
  },
  notifications: {
    usageTitle: "Hâlâ kullanıyor musun?",
    usageBody: (name: string) => `${name} için bir kontrol zamanı geldi.`,
  },
  data: {
    importDone: "İçe aktarıldı",
    importDoneCount: (n: number) => `${n} gider eklendi/güncellendi.`,
    importNone: "Dosyada geçerli gider bulunamadı.",
    importFail: "İçe aktarma başarısız",
    importFailBody:
      "Geçerli bir JSON dosyası seç (uygulamadan dışa aktardığın gider dosyası).",
  },
  portfolio: {
    tab: "Portföy",
    add: "Hisse Ekle",
    editTitle: "Hisseyi Düzenle",
    detail: "Hisse Detayı",
    symbol: "Sembol",
    symbolPlaceholder: "örn. THYAO, AAPL",
    market: "Piyasa",
    marketBist: "BIST",
    marketUs: "ABD",
    marketEmtia: "Emtia",
    commodity: "Emtia",
    quantity: "Adet",
    quantityGram: "Gram",
    costBasis: "Hisse Başı Maliyet",
    costBasisGram: "Gram Başı Maliyet",
    costCurrency: "Maliyet Para Birimi",
    notes: "Notlar",
    save: "Kaydet",
    delete: "Tamamen sil",
    deleteTitle: "Hisse silinsin mi?",
    deleteBody: "Bu hisse kaydı kalıcı olarak silinecek.",
    summaryTitle: "Özet",
    hiddenValue: "******",
    totalCost: "Toplam Maliyet",
    totalValue: "Güncel Değer",
    gain: "Kâr/Zarar",
    refreshPrices: "Fiyatları Yenile",
    refreshDoneTitle: "Fiyatlar güncellendi",
    refreshDoneBody: (n: number) => `${n} kayıt için güncel fiyat alındı.`,
    refreshFailTitle: "Fiyat alınamadı",
    refreshFailBody:
      "Yahoo Finance veya web proxy yanıt vermedi. Biraz sonra tekrar dene ya da mobilde yenile.",
    modeAll: "Tümü",
    modeDaily: "Günlük",
    noteAll: "Aldığın fiyata (maliyetine) göre toplam kâr/zarar.",
    noteDaily: "Bugünkü piyasa hareketine göre (önceki kapanışa kıyasla) kâr/zarar.",
    profitUnavailable: "Hesaplamak için fiyat verisi yok.",
    priceUnavailable: "Fiyat henüz çekilmedi",
    empty: "Henüz hisse eklenmedi. İlk hissenin maliyetini ekle.",
    emptyAdd: "İlk hisseni ekle",
    notFound: "Hisse bulunamadı",
    costLabel: (qty: string, total: string, unit: string = "adet") => `${qty} ${unit} • ${total}`,
  },
} as const;
